# Generated by Django 5.2 on 2025-05-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('users', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myuser',
            new_name='User',
        ),
    ]
